### ISSUE TITLE
GraphiQL custom endpoints

### ISSUE THREAD

**Issue by tobolleo** [thecodingmachine/graphqlite-bundle#105]
Hello, how am I supposed to define my custom graphQL endpoint for GraphiQL GUI? In the original [documentation](https://github.com/overblog/GraphiQLBundle/blob/master/Resources/doc/graphql-endpoint.md) of GraphiQL it's described pretty well. But when using graphqlite-bundle, changing of parameter` overblog_graphiql.endpoint_resolver` does not take any effect.  Is there any simple way to define custom endpoints for GraphiQL GUI when using graphqlite-bundle?

Thank you.

**Comment by TamasSzigeti** [comment]
This is what we use:

```
graphqliteRoute:
    path: /graphql
    methods: POST
    controller: 'TheCodingMachine\Graphqlite\Bundle\Controller\GraphqliteController::handleRequest'

overblog_graphiql_endpoint:
    path: /graphql
    methods: GET
    controller: 'Overblog\GraphiQLBundle\Controller\GraphiQLController::indexAction'
```

Plus we have an extra env-based `condition` key on the latter to disable it in production

This is to replace the default routing config for both packages
