### ISSUE TITLE
Using namespaces not covered by autoload attribute of composer.json in types config is not supported

### ISSUE THREAD

**Issue by tigitz** [thecodingmachine/graphqlite-bundle#89]
Following https://github.com/thecodingmachine/graphqlite/issues/333

When you specify a namespace in `types` configuration:

```yaml
graphqlite:
  namespace:
    types:
      - Company1\Package1\SharedModel\UUID
```

That is not covered by the namespace defined in the `autoload` attribute of the composer.json:
```json
"autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
```

It's not working.

After some investigation it's due to:
https://github.com/thecodingmachine/graphqlite-bundle/blob/a14b9a0313e0bd788d33a08ca98fb2bc845fb371/DependencyInjection/GraphqliteCompilerPass.php#L478

Where `ClassNameMapper::createFromComposerFile` is used but it unfortunately only retrieves classes that are namespaced with namespaces declared in the `autoload` attribute of the composer.json file

**Comment by tigitz** [comment]
@oojacoboo Here's an, hopefully, clearer explanation.

I took some time to think about a solution and I think it could be addressed by providing an additional way to define types.

```
graphqlite:
  namespace:
    types:
     # Could be the default way to import types with a requirement of having this class covered by the autoload
      - App\Model\Type
     # For "non-autoload-covered" namespaces
     - {namespace: 'Vendor\Package\Type', path:'../../vendor/package/'}
```

And build the classNameMapper this way:
```php
// Take care of composer autoload namespace
$classNameMapper = ClassNameMapper::createFromComposerFile(null, null, true);
// Take care of non composer autoload namespace
$classNameMapper->registerPsr4Namespace($namespace, $path);
```

Although I'm not familiar with the internal and I'm wondering if something similar to doctrine typing can be achieved as this ORM config allows exactly what I'm trying to achieve with graphql mapping which is using mapping that don't necessarily belong to the "app" itself.

```yaml
doctrine:
    orm:
        mappings:
            Inventory:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/../vendor/Company/Package/Inventory/src'
                prefix: 'Company\Inventory'
                alias: Inventory
```

I know @moufmouf is quite busy these days but if he can chime in to provide his opinion quickly that would be awesome as it would remove the last barrier for my company to go all-in on graphqlite and support the development.
